### ISSUE TITLE
Splitting Sparks.js Source into Files

### ISSUE THREAD

**Issue by zz85** [zz85/sparks.js#11]
Usually I try to keeping as much code as possible in a js file if possible, but as more classes are being developed, there would be the need to split them into separate files and folders.

When that time comes, we could consider using UglifyJS or Google Closure Compiler for building the source files.

**Comment by jeromeetienne** [comment]
I would love to have a just core and many plugins.

It would so easy to hack with, and the core would be so small

**Comment by zz85** [comment]
Source files are now being split in the new branch https://github.com/zz85/sparks.js/tree/m2 but build files would be combined into a single file.

**Comment by jeromeetienne** [comment]
Hey

I thinks this lib needs more love. And a massive clean up :) i could write it and propose it. But the api wont be compatible... How would you feel abput that ?

Jerome

**Comment by zz85** [comment]
I've open a new issue if you have suggestions. Feel free to discuss this at Issue #17
