### ISSUE TITLE
A defect may need to be fixed

### ISSUE THREAD

**Issue by chilicomputer** [zz85/sparks.js#12]
In Sparks.js line 113, its written that " this_.activities[i].update( this, time )".
I think it should be "this._activities[i].update( this, time )" with "_" after "this".
Maybe this defect does not let the engine down, but I'm confused about what's the effect of "this._activities"？
Since I can't find any methods to add activities to emitter._activities in the Sparks.js .

All my best & Thax for this brilliant engine!

**Comment by zz85** [comment]
@chilicomputer thanks for highlighting this, although there are currently no activities are not being created or used.

Just like how `Actions` affects particles, `Activities` affects the Emitter.

Potential activities could be `MoveEmitterAlongPathActivity` or `MoveEmitterToCursorActivity`. Any other suggestions are welcome! :)

**Comment by zz85** [comment]
the typo has been correctly in the current repository. thanks! :)
