### ISSUE TITLE
Lastest Three.js lib

### ISSUE THREAD

**Issue by tud0r** [zz85/sparks.js#18]
Hey was just checking out your example here
http://jabtunes.com/labs/particles/webgl_particles_shapes.html

For some reason when I update the urls for the js libraries to a relative urls pointing  to my local copies of the Three.js it doesn't work ?
RequestAnimationFrame.js doesn't seem to be in the examples directory in the lastest version of the Three.js library 

I was wondering if the example is out of date with the newest version of the Three.js Library?

Thanks

T

**Comment by tud0r** [comment]
Updated the relevant lines to work with the latest Three.js library

**Comment by zz85** [comment]
@tud0r yes, that's because the three.js library api has changed.

the examples in this github repository or even those on the three.js repo should work.

http://mrdoob.github.com/three.js/examples/webgl_particles_shapes.html

**Comment by tud0r** [comment]
Cool thanks
