### ISSUE TITLE
"initialized" event ?

### ISSUE THREAD

**Issue by jeromeetienne** [zz85/sparks.js#2]
many examples contains a "initialized" event which is never called from Sparks.js

is that obsolete code ?

**Comment by jeromeetienne** [comment]
pull request welcomed if i remove them ?

**Comment by zz85** [comment]
yes, i guessed that's obsolete code. 

the event `created` is used after a particle gets generated, and perhaps i was thinking of using `initialized` as a callback event after the emitter got initialized.

i'll be happy to accept a pull request! :)

**Comment by jeromeetienne** [comment]
pull request #5

**Comment by zz85** [comment]
thanks again, jerome! :)
