### ISSUE TITLE
examples/CanvasShaders.js barely used ?

### ISSUE THREAD

**Issue by jeromeetienne** [zz85/sparks.js#3]
- canvas examples uses various shapes for particles material.
- Most examples got their own copy of this drawing code. 
- CanvasShaders.js would avoid this duplication but it is barely used

Why that ? historical reason ?

**Comment by jeromeetienne** [comment]
pull request welcomed if i remove the duplicated code for canvas drawing material ?

**Comment by zz85** [comment]
you are right. `CanvasShaders.js` was meant to avoid duplicated code, but i was hastily doing "copy and paste". i'll be glad to do pull request again.

**Comment by jeromeetienne** [comment]
pull request submitted

**Comment by zz85** [comment]
thanks for the work jerome! :)
