### ISSUE TITLE
no removeAction/removeInitializer ?

### ISSUE THREAD

**Issue by jeromeetienne** [zz85/sparks.js#8]
- there is a `addAction` but no `removeAction``
- there is a `addInitilizer` but no `remove Initializer`

So it is quite hard to remove stuff put in the stack.

**Comment by zz85** [comment]
feature added. https://github.com/zz85/sparks.js/commit/2d28a191587de75477ea23f6a3c8c4ac5b62fd1b

sample:

```
            lf = new SPARKS.Lifetime(5,10)
            sparksEmitter.addInitializer(lf);
            sparksEmitter.removeInitializer(lf);


            a = new SPARKS.Accelerate( 40, -100, 50  )
            sparksEmitter.addAction( a );
            sparksEmitter.removeAction( a );
```

**Comment by jeromeetienne** [comment]
thanks :)
