### ISSUE TITLE
particle editor ?

### ISSUE THREAD

**Issue by jeromeetienne** [zz85/sparks.js#9]
- is there an editor to edit particles in a sparks.js compatible manner ?
- it helps quite a bit non tech people to produce nice looking particle

**Comment by jeromeetienne** [comment]
ok ok it is a bit theorical issue :) i will write such editor as i need for my own purpose. aka design effects for games. the 2 stacks init/actions makes the editor quite easy to understand i think. we will see. i will update this issue with progress

**Comment by zz85** [comment]
Btw, do you mean a particle editor in the form of a code editor or a UI editor?

I currently have no plans to work on a UI editor yet, until the library has become more matured. But either ways, both would be good to have.  :)

**Comment by jeromeetienne** [comment]
I was thinking about a ui editor. I think i can write something usefull with basic dom widget.

In my experience, Particles need an editor to be used in the field. The ui editor makes it much faster to design a given effect, even for me, a coder. Well we will see :)

**Comment by zz85** [comment]
I had some simple UI to help me tweak parameters for spark.js http://www.jabtunes.com/labs/arabesque/developer.html but a simple graphical UI to configuring sparks.js would be great.

**Comment by jeromeetienne** [comment]
i did some progress on the editor side

http://jeromeetienne.github.com/sparks.js/editor/ a half backed version with widget

http://jeromeetienne.github.com/sparks.js/editor2/ with a inline code editor

comparison and why i prefer the inline code editor version: 
- **pro:** you got full javascript flexibility... for examples the hue+closure in the heart example
- **pro:** the editor is much easier to code/maintained :)
- **con:** require programming knowledge
- **con:** less visual (not cool to pick color for example)

What do you think ?

**Comment by zz85** [comment]
not bad :)

i think that a gui editor would be useful to a beginners or to an experienced user to some fast prototyping. however, it may be quite an amount work to be done to integrate widgets to the library unless its done in an extensible maner.

some examples of such work which have been done before and can be seen at http://flexmonkey.blogspot.com/2010/03/flex-flint-particles-editor-with-node.html and http://idflood.github.com/ThreeNodes.js/

A code editor has its advantages, its useful for fast previews, and useful for showing snippets for examples and learning.

A code editor could also integrate color pickers or other utilities. For example, see http://dabblet.com/

**Comment by jeromeetienne** [comment]
coded and published at https://github.com/jeromeetienne/sparkseditor 

closing :)

**Comment by zz85** [comment]
nice work, and <a href="https://github.com/idflood/ThreeNodes.js">threenode.js</a> also have some support for spark.js now.
